// Package conformance houses the executable 12-factor conformance suite
// for aim. Each TestFactor* test maps to one factor in the upstream
// 12-factor AI-CLI spec and locks the contract by exercising the
// production wiring (cmd/aim/main.go's command tree, kit's WrapRunE
// middleware, real cache + breaker code paths).
//
// The suite is in-process: every test composes a *cli.Root identical to
// production, calls Cmd.ExecuteContext directly, and asserts on stdout
// + stderr buffers. No subprocess spawn, no network. The cache is
// primed from testdata/api-fixture.json into a per-test XDG temp dir.
//
// See docs/12-factor-conformance.md (auto-regenerated by
// TestGenerateReport) for the canonical PASS/FAIL matrix.
package conformance

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/spf13/cobra"

	"hop.top/aim/internal/apiversion"
	aimcmd "hop.top/aim/internal/cmd"
	"hop.top/aim/internal/status"
	speccli "hop.top/kit/go/ai/toolspec/cli"
	"hop.top/kit/go/console/cli"
	"hop.top/kit/go/console/output"
)

// asOutputError type-asserts v to *output.Error. Returns nil when v is
// not an *output.Error or when v is nil. Used by Factor 4 to read
// the envelope fields directly without re-serialising.
func asOutputError(v any) *output.Error {
	if v == nil {
		return nil
	}
	if e, ok := v.(*output.Error); ok {
		return e
	}
	return nil
}

const (
	// aimVersion is the version pinned on the production Root in
	// cmd/aim/main.go. Kept in sync here so the manifest emitted by
	// `aim spec` reports the right value in the conformance run.
	aimVersion = "0.1.0"
)

// fixturePath returns the absolute path to the shipped api-fixture.
// Mounted at testdata/api-fixture.json in the repo root; tests run
// from internal/conformance/.
func fixturePath(t *testing.T) string {
	t.Helper()
	p := filepath.Join("..", "..", "testdata", "api-fixture.json")
	if _, err := os.Stat(p); err != nil {
		t.Fatalf("fixture missing at %s: %v", p, err)
	}
	return p
}

// fixtureBytes loads the api-fixture.json payload.
func fixtureBytes(t *testing.T) []byte {
	t.Helper()
	b, err := os.ReadFile(fixturePath(t))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	return b
}

// primeXDGCache writes the fixture into $XDG_CACHE_HOME/hop/aim/ with
// meta.json set to a recent fetch under the default TTL. Returns the
// resolved cache directory path.
//
// The test that calls primeXDGCache sees an environment whose cache
// looks identical to one populated by a real `aim refresh`.
func primeXDGCache(t *testing.T) string {
	t.Helper()
	xdg := t.TempDir()
	t.Setenv("XDG_CACHE_HOME", xdg)
	dir := filepath.Join(xdg, "hop", "aim")
	if err := os.MkdirAll(dir, 0o750); err != nil {
		t.Fatalf("mkdir cache dir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "models-dev.json"), fixtureBytes(t), 0o600); err != nil {
		t.Fatalf("write payload: %v", err)
	}
	meta := struct {
		LastFetch  time.Time `json:"last_fetch"`
		ETag       string    `json:"etag,omitempty"`
		TTLSeconds int64     `json:"ttl_seconds"`
	}{
		LastFetch:  time.Now().Add(-1 * time.Hour).UTC(),
		ETag:       "W/\"conformance\"",
		TTLSeconds: int64((24 * time.Hour).Seconds()),
	}
	mb, err := json.Marshal(meta)
	if err != nil {
		t.Fatalf("marshal meta: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "meta.json"), mb, 0o600); err != nil {
		t.Fatalf("write meta: %v", err)
	}
	return dir
}

// newRoot constructs a Root with the same wiring as cmd/aim/main.go
// (status providers, every adopter leaf, kit-shipped spec + status,
// the api-version guard). DisableValidate keeps the construction-time
// shape validator out of the way so individual factor tests can drive
// the tree without tripping unrelated checks.
func newRoot(t *testing.T) *cli.Root {
	t.Helper()
	root := cli.New(cli.Config{
		Name:            "aim",
		Version:         aimVersion,
		Short:           "aim conformance test",
		Accent:          "#7DFFB3",
		DisableValidate: true,
	}, cli.WithStatus(cli.StatusConfig{
		ExtraEnvKeys: []string{"AIM_*", "XDG_*", "NO_COLOR", "GOWORK"},
	}))
	status.Register(root, aimVersion)
	root.Cmd.AddCommand(
		aimcmd.ListCmd(root),
		aimcmd.ShowCmd(root),
		aimcmd.ProvidersCmd(root),
		aimcmd.RefreshCmd(root),
		aimcmd.QueryCmd(root),
	)
	if err := speccli.RegisterSpecCommand(root, apiversion.Current); err != nil {
		t.Fatalf("register spec: %v", err)
	}
	installAPIVersionGuard(root)
	root.WrapRunE()
	return root
}

// installAPIVersionGuard mirrors cmd/aim/main.go's leaf-RunE wrapper
// so the api-version negotiation runs under the same path as
// production. Kept here (rather than importing main) because main is
// package main and cannot be imported by other packages.
func installAPIVersionGuard(root *cli.Root) {
	walkCommands(root.Cmd, func(c *cobra.Command) {
		if c.RunE == nil {
			return
		}
		inner := c.RunE
		c.RunE = func(cmd *cobra.Command, args []string) error {
			var requested string
			if root.Viper != nil {
				requested = root.Viper.GetString("api-version")
			}
			if _, envErr := apiversion.Negotiate(requested); envErr != nil {
				return envErr
			}
			return inner(cmd, args)
		}
	})
}

// walkCommands invokes fn on cmd and every transitively-attached child.
func walkCommands(cmd *cobra.Command, fn func(*cobra.Command)) {
	if cmd == nil {
		return
	}
	fn(cmd)
	for _, child := range cmd.Commands() {
		walkCommands(child, fn)
	}
}

// runCmd executes argv against root, capturing stdout + stderr. The
// returned err is the cobra/RunE error (nil on success). Stdout and
// stderr are returned as strings for substring/JSON assertions.
//
// IMPORTANT: Cmd.SetArgs is sticky across invocations on the same
// root; tests reset to a fresh root via newRoot or via dispatch_fresh.
func runCmd(t *testing.T, root *cli.Root, argv ...string) (stdout, stderr string, err error) {
	t.Helper()
	var sb, eb bytes.Buffer
	root.Cmd.SetOut(&sb)
	root.Cmd.SetErr(&eb)
	root.Cmd.SetArgs(argv)
	err = root.Cmd.ExecuteContext(context.Background())
	return sb.String(), eb.String(), err
}

// parseEnvelope decodes the first balanced JSON object from s. Used
// for both success envelopes (stdout) and error envelopes (stderr).
// Fails the test if no balanced object exists.
func parseEnvelope(t *testing.T, s string) map[string]any {
	t.Helper()
	start := strings.Index(s, "{")
	if start < 0 {
		t.Fatalf("no JSON object in output: %q", s)
	}
	depth := 0
	end := -1
	for i := start; i < len(s); i++ {
		switch s[i] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				end = i + 1
			}
		}
		if end > 0 {
			break
		}
	}
	if end < 0 {
		t.Fatalf("no balanced JSON object in output: %q", s)
	}
	var m map[string]any
	if err := json.Unmarshal([]byte(s[start:end]), &m); err != nil {
		t.Fatalf("envelope parse: %v\nraw: %s", err, s[start:end])
	}
	return m
}

// envelopeMeta returns the _meta map from a parsed envelope, or fails
// the test if absent.
func envelopeMeta(t *testing.T, env map[string]any) map[string]any {
	t.Helper()
	meta, ok := env["_meta"].(map[string]any)
	if !ok {
		t.Fatalf("_meta missing or wrong type in envelope: %#v", env)
	}
	return meta
}

// leafCommands walks root and returns every leaf (RunE-bearing) cobra
// command. The conformance test iterates these for factor 5 / 9
// contract + hint assertions.
func leafCommands(root *cli.Root) []*cobra.Command {
	var out []*cobra.Command
	walkCommands(root.Cmd, func(c *cobra.Command) {
		// Skip the root itself, hidden helper commands, and any node
		// without a RunE (intermediates).
		if c == root.Cmd {
			return
		}
		if c.RunE == nil && c.Run == nil {
			return
		}
		out = append(out, c)
	})
	return out
}

// ensureWriters drops stdout/stderr writes that aren't useful for the
// caller (used by helpers that want to invoke a command for its side
// effect only). Returns a teardown func that restores writers.
//
//nolint:unused // reserved for future helpers
func ensureWriters(root *cli.Root, w io.Writer) func() {
	prevOut, prevErr := root.Cmd.OutOrStdout(), root.Cmd.ErrOrStderr()
	root.Cmd.SetOut(w)
	root.Cmd.SetErr(w)
	return func() {
		root.Cmd.SetOut(prevOut)
		root.Cmd.SetErr(prevErr)
	}
}

