package conformance

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// reportRow is one factor's metadata for the auto-generated
// conformance report.
type reportRow struct {
	Factor      int
	Title       string
	Tier        string // MUST | SHOULD
	TestName    string
	Evidence    string // file path the test exercises
}

// reportRows enumerates the 12-factor matrix in canonical order. Edit
// here when factor scope or evidence path changes.
var reportRows = []reportRow{
	{1, "Capability Introspection", "MUST", "TestFactor1Introspection",
		"cmd/aim/main.go RegisterSpecCommand; per-leaf cli.SetOutputSchema/Examples/NextSteps"},
	{2, "Intent Clarity", "MUST", "TestFactor2Intent",
		"internal/cmd/list.go positional warning; internal/cmd/show.go flag aliases"},
	{3, "Structured I/O", "MUST", "TestFactor3StructuredIO",
		"internal/cmd/* output.Render with WithProvenance; envelopeWithWarnings"},
	{4, "Structured Error Recovery", "MUST", "TestFactor4Errors",
		"internal/errs/errs.go constructors; kit WrapRunE renderer"},
	{5, "Capability Contracts", "MUST", "TestFactor5Contracts",
		"per-leaf cli.SetSideEffect/Idempotency/OutputSchema/Examples"},
	{6, "Preview & Explain", "SHOULD", "TestFactor6Preview",
		"internal/cmd/refresh.go runRefreshDryRun; internal/cmd/query.go --explain"},
	{7, "Idempotency", "MUST", "TestFactor7Idempotency",
		"aim.Cache TTL + ETag handling; cli.SetIdempotency(IdempotencyYes) per leaf"},
	{8, "State Transparency", "MUST", "TestFactor8State",
		"cli.WithStatus + internal/status/*.go providers in cmd/aim/main.go"},
	{9, "Contextual Guidance", "SHOULD", "TestFactor9Guidance",
		"internal/cmd/hints.go registerHints + installHintEmitter"},
	{10, "Resilient Delegation", "MUST", "TestFactor10Delegation",
		"aim.SourceBreaker + ModelsDevSource.Fetch; status source-breaker provider"},
	{11, "Provenance", "MUST", "TestFactor11Provenance",
		"internal/cmd/provenance.go provenanceFromCache / provenanceForRefresh"},
	{12, "Evolution Guarantees", "MUST", "TestFactor12Evolution",
		"internal/apiversion/apiversion.go Negotiate; docs/schema-changelog.md"},
}

// TestGenerateReport regenerates docs/12-factor-conformance.md from the
// reportRows matrix above. It runs every factor test as a sub-test so a
// failure inline blocks the regeneration with a non-zero exit.
//
// The output is fully deterministic — no wall-clock timestamp, no
// commit SHA. Provenance lives in git itself: `git log -1
// docs/12-factor-conformance.md` shows when it was last regenerated
// and against which commit. CI's diff guard depends on byte-identical
// output across re-runs.
func TestGenerateReport(t *testing.T) {
	statuses := make(map[string]string, len(reportRows))
	for _, row := range reportRows {
		passed := t.Run(row.TestName, func(t *testing.T) {
			runFactorByName(t, row.TestName)
		})
		if passed {
			statuses[row.TestName] = "PASS"
		} else {
			statuses[row.TestName] = "FAIL"
		}
	}

	passCount := 0
	for _, s := range statuses {
		if s == "PASS" {
			passCount++
		}
	}
	failCount := len(statuses) - passCount

	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("title: aim 12-Factor AI-CLI Conformance Report\n")
	b.WriteString("status: auto-generated\n")
	b.WriteString("owner: aim\n")
	b.WriteString("---\n\n")
	b.WriteString("# 12-Factor AI-CLI Conformance Report\n\n")
	b.WriteString("> Auto-generated by `go test -run TestGenerateReport ./internal/conformance/...`.\n")
	b.WriteString("> Do not edit by hand — re-run the test to refresh.\n\n")
	b.WriteString("Provenance: this file is fully derived from the matrix below; ")
	b.WriteString("run `git log -1 docs/12-factor-conformance.md` to see when it was last regenerated.\n\n")
	fmt.Fprintf(&b, "Summary: **%d/%d PASS** — %d failing\n\n",
		passCount, len(reportRows), failCount)

	b.WriteString("## Matrix\n\n")
	b.WriteString("| # | Factor | Tier | Test | Status | Evidence |\n")
	b.WriteString("|---|--------|------|------|--------|----------|\n")
	for _, row := range reportRows {
		status := statuses[row.TestName]
		icon := "PASS"
		if status == "FAIL" {
			icon = "FAIL"
		}
		fmt.Fprintf(&b, "| %d | %s | %s | `%s` | %s | %s |\n",
			row.Factor, row.Title, row.Tier, row.TestName, icon, row.Evidence)
	}
	b.WriteString("\n## How to reproduce\n\n")
	b.WriteString("```\n")
	b.WriteString("GOWORK=off go test -buildvcs=false -count=1 -run TestFactor ./internal/conformance/...\n")
	b.WriteString("GOWORK=off go test -buildvcs=false -count=1 -run TestGenerateReport ./internal/conformance/...\n")
	b.WriteString("```\n\n")
	b.WriteString("The first command runs every factor test in isolation; the second ")
	b.WriteString("regenerates this report. Commit both the test results and the report.\n")

	dest := filepath.Join("..", "..", "docs", "12-factor-conformance.md")
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		t.Fatalf("mkdir docs: %v", err)
	}
	if err := os.WriteFile(dest, []byte(b.String()), 0o644); err != nil {
		t.Fatalf("write %s: %v", dest, err)
	}
	t.Logf("regenerated %s (%d PASS, %d FAIL)", dest, passCount, failCount)
}

// runFactorByName dispatches to the right TestFactor* body. We use an
// explicit switch (rather than reflection) so the call graph is easy
// to audit and a missing name fails loudly.
func runFactorByName(t *testing.T, name string) {
	switch name {
	case "TestFactor1Introspection":
		TestFactor1Introspection(t)
	case "TestFactor2Intent":
		TestFactor2Intent(t)
	case "TestFactor3StructuredIO":
		TestFactor3StructuredIO(t)
	case "TestFactor4Errors":
		TestFactor4Errors(t)
	case "TestFactor5Contracts":
		TestFactor5Contracts(t)
	case "TestFactor6Preview":
		TestFactor6Preview(t)
	case "TestFactor7Idempotency":
		TestFactor7Idempotency(t)
	case "TestFactor8State":
		TestFactor8State(t)
	case "TestFactor9Guidance":
		TestFactor9Guidance(t)
	case "TestFactor10Delegation":
		TestFactor10Delegation(t)
	case "TestFactor11Provenance":
		TestFactor11Provenance(t)
	case "TestFactor12Evolution":
		TestFactor12Evolution(t)
	default:
		t.Fatalf("runFactorByName: unknown test %q", name)
	}
}
